project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AxesAccess
      - icon: linkedin
        href: https://www.linkedin.com/in/telecamera/
  google-analytics: "G-H2HYLD7LV5"
format:
  html:
    theme: litera
    css: styles.css
editor: visual

