project:
  type: website

website:
  title: "Blog"
  site-url: "https://blog.frequentist.org"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AxesAccess
      - icon: linkedin
        href: https://www.linkedin.com/in/aleksei-pr
      - icon: rss
        href: https://blog.frequentist.org/index.xml
  google-analytics: "G-H2HYLD7LV5"
  cookie-consent:
    type: implied
    palette: dark
  open-graph: true
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: sandstone
      dark: darkly
    css: styles.css
editor: visual

resources:
  - "posts/20250927-credit-risk-analytics/*.html"
  - "posts/20250927-credit-risk-analytics/*/libs/bootstrap/*"
  - "posts/20250927-credit-risk-analytics/*/libs/clipboard/*"
  - "posts/20250927-credit-risk-analytics/*/libs/quarto-html/*"
  - "posts/20250927-credit-risk-analytics/*/figure-html/*"

  - "posts/20251026-cfpb-dashboard/*.html"
  - "posts/20251026-cfpb-dashboard/*/libs/bootstrap/*"
  - "posts/20251026-cfpb-dashboard/*/libs/clipboard/*"
  - "posts/20251026-cfpb-dashboard/*/libs/quarto-html/*"
  - "posts/20251026-cfpb-dashboard/*/figure-html/*"

  - "posts/20251126-e-commerce-dashboard/*.html"
  - "posts/20251126-e-commerce-dashboard/*/libs/bootstrap/*"
  - "posts/20251126-e-commerce-dashboard/*/libs/clipboard/*"
  - "posts/20251126-e-commerce-dashboard/*/libs/quarto-html/*"
  - "posts/20251126-e-commerce-dashboard/*/figure-html/*"
